// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhnhqsjmicxkhzqvrjko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpobmhxc2ptaWN4a2h6cXZyamtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTM4OTgsImV4cCI6MjA3MzY2OTg5OH0.e-snq26CQiD3GYzqPmv60tG13ZVDeBrMv3VNfS4HZxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});